# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-22 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MajorArcana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(0, 'The Fool'), (1, 'The Magician'), (2, 'The High Priestess'), (3, 'The Empress'), (4, 'The Emperor'), (5, 'The Hierophant'), (6, 'The Lovers'), (7, 'The Chariot'), (8, 'Strength'), (9, 'The Hermit'), (10, 'Wheel of Fortune'), (11, 'Justice'), (12, 'The Hanged Man'), (13, 'Death'), (14, 'Temperance'), (15, 'The Devil'), (16, 'The Tower'), (17, 'The Star'), (18, 'The Moon'), (19, 'The Sun'), (20, 'Judgement'), (21, 'The World')])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MinorArcana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(choices=[(1, 'Ace'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten'), (11, 'Page'), (12, 'Knight'), (13, 'Queen'), (14, 'King')])),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Suit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='minorarcana',
            name='suit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learn.Suit'),
        ),
    ]
