# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-22 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0002_auto_20170922_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
